import { client } from '../../lib/sanity/client';
import type { ProcessedArticle } from './ai-processor';

// 生成 slug
function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 50);
}

// 检查文章是否已存在
async function checkDuplicate(title: string): Promise<boolean> {
  const query = `*[_type == "article" && title.zh == "${title}"][0]`;
  const existing = await client.fetch(query);
  return !!existing;
}

// 获取分类 ID
async function getCategoryId(categorySlug: string): Promise<string | null> {
  const query = `*[_type == "articleCategory" && slug.current == "${categorySlug}"][0]._id`;
  return await client.fetch(query);
}

// 发布文章到 Sanity
export async function publishArticle(
  processed: ProcessedArticle,
  sourceUrl: string,
  sourceName: string
): Promise<boolean> {
  try {
    // 检查重复
    const isDuplicate = await checkDuplicate(processed.title.zh);
    if (isDuplicate) {
      console.log(`  ⚠️ Article already exists: ${processed.title.zh}`);
      return false;
    }
    
    // 获取分类 ID
    const categoryId = await getCategoryId(processed.category);
    if (!categoryId) {
      console.error(`  ✗ Category not found: ${processed.category}`);
      return false;
    }
    
    // 构建 Sanity 文档
    const doc = {
      _type: 'article',
      title: processed.title,
      slug: {
        current: generateSlug(processed.title.zh),
      },
      category: {
        _type: 'reference',
        _ref: categoryId,
      },
      tags: processed.tags,
      excerpt: processed.excerpt,
      content: {
        zh: [
          {
            _type: 'block',
            style: 'normal',
            children: [
              {
                _type: 'span',
                text: processed.content.zh,
              },
            ],
          },
        ],
        en: [
          {
            _type: 'block',
            style: 'normal',
            children: [
              {
                _type: 'span',
                text: processed.content.en || processed.content.zh,
              },
            ],
          },
        ],
        id: [
          {
            _type: 'block',
            style: 'normal',
            children: [
              {
                _type: 'span',
                text: processed.content.id || processed.content.en || processed.content.zh,
              },
            ],
          },
        ],
        th: [
          {
            _type: 'block',
            style: 'normal',
            children: [
              {
                _type: 'span',
                text: processed.content.th || processed.content.en || processed.content.zh,
              },
            ],
          },
        ],
        vi: [
          {
            _type: 'block',
            style: 'normal',
            children: [
              {
                _type: 'span',
                text: processed.content.vi || processed.content.en || processed.content.zh,
              },
            ],
          },
        ],
        ar: [
          {
            _type: 'block',
            style: 'normal',
            children: [
              {
                _type: 'span',
                text: processed.content.ar || processed.content.en || processed.content.zh,
              },
            ],
          },
        ],
      },
      publishedAt: new Date().toISOString(),
      status: 'published',
      author: {
        name: 'GOPRO LED',
      },
      source: {
        url: sourceUrl,
        name: sourceName,
        isAutoGenerated: true,
      },
      seo: {
        metaTitle: processed.seo.metaTitle,
        metaDescription: processed.seo.metaDescription,
        keywords: processed.seo.keywords,
      },
      viewCount: 0,
      isFeatured: false,
    };
    
    // 创建文档
    const result = await client.create(doc);
    console.log(`  ✅ Published: ${result._id}`);
    
    return true;
  } catch (error) {
    console.error('  ✗ Publish failed:', error);
    return false;
  }
}

// 批量发布
export async function publishArticles(
  articles: ProcessedArticle[],
  sourceMap: Map<string, { url: string; name: string }>
): Promise<number> {
  let published = 0;
  
  for (const article of articles) {
    // 找到对应的 source 信息
    const source = sourceMap.get(article.title.zh);
    if (!source) {
      console.log(`  ⚠️ Source not found for: ${article.title.zh}`);
      continue;
    }
    
    const success = await publishArticle(article, source.url, source.name);
    if (success) {
      published++;
    }
    
    // 避免API限流
    await new Promise(resolve => setTimeout(resolve, 1000));
  }
  
  return published;
}
